// 3474. Lexicographically Smallest Generated String
// Example 1:
// Input: str1 = "TFTF", str2 = "ab"
// Output: "ababa"
// Explanation:
// The table below represents the string "ababa"
// Index	T/F	Substring of length m
// 0	'T'	"ab"
// 1	'F'	"ba"
// 2	'T'	"ab"
// 3	'F'	"ba"
// The strings "ababa" and "ababb" can be generated by str1 and str2.
// Return "ababa" since it is the lexicographically smaller string.
// Example 2:
// Input: str1 = "TFTF", str2 = "abc"
// Output: ""
// Explanation:
// No string that satisfies the conditions can be generated.
// Example 3:
// Input: str1 = "F", str2 = "d"
// Output: "a"
#include <iostream>
#include <vector>
using namespace std;

bool isSame(string &word, string &str2, int i, int m) {
    for (int j = 0; j < m; j++) {
        if (word[i + j] != str2[j]) {
            return false;
        }
    }
    return true;
}

string generateString(string str1, string str2) {
    int n = str1.length();
    int m = str2.length();

    int N = n + m - 1;
    string word(N, '$');

    vector<bool> canChange(N, false);

    // Step 1: Handle 'T'
    for (int i = 0; i < n; i++) {
        if (str1[i] == 'T') {
            for (int j = 0; j < m; j++) {
                if (word[i + j] != '$' && word[i + j] != str2[j]) {
                    return "";
                }
                word[i + j] = str2[j];
            }
        }
    }

    // Step 2: Fill remaining with 'a'
    for (int i = 0; i < N; i++) {
        if (word[i] == '$') {
            word[i] = 'a';
            canChange[i] = true;
        }
    }

    // Step 3: Handle 'F'
    for (int i = 0; i < n; i++) {
        if (str1[i] == 'F') {
            if (isSame(word, str2, i, m)) {

                bool changed = false;
                for (int k = i + m - 1; k >= i; k--) {
                    if (canChange[k]) {
                        word[k] = 'b';  // break equality
                        changed = true;
                        break;
                    }
                }

                if (!changed) return "";
            }
        }
    }

    return word;
}

int main() {
    string str1 = "TFTF";
    string str2 = "ab";

    cout << generateString(str1, str2);

    return 0;
